begin;
alter table public.profiles add column lifecycle text not null default 'approved' check(lifecycle in ('pending_verification','pending_review','approved','rejected','suspended','deletion_requested')),add column email_verified_at timestamptz,add column customer_terms boolean not null default false;
-- Use Auth's actual confirmation evidence, never an invented verification timestamp.
update public.profiles p set email_verified_at=(to_jsonb(u)->>'email_confirmed_at')::timestamptz,lifecycle=case when to_jsonb(u)->>'email_confirmed_at' is null then 'pending_verification' else 'pending_review' end from auth.users u where u.id=p.id and p.demo_workspace is null and not p.suspended;
alter table public.user_roles add column status text not null default 'approved' check(status in ('pending_verification','pending_review','approved','rejected','suspended'));
create table public.agreement_versions(id uuid primary key default gen_random_uuid(),kind text not null check(kind in ('vendor','runner','customer')),version text not null check(length(version) between 1 and 60),title text not null,sections jsonb not null check(jsonb_typeof(sections)='array' and jsonb_array_length(sections) between 2 and 30),source_sha256 text not null check(source_sha256~'^[0-9a-f]{64}$'),active boolean not null default false,created_at timestamptz not null default now(),unique(kind,version));
create unique index active_agreement_kind on public.agreement_versions(kind) where active;
create table public.role_applications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,role text not null check(role in ('vendor','runner')),status text not null default 'draft' check(status in ('draft','submitted','under_review','approved','rejected')),payload jsonb not null default '{}' check(octet_length(payload::text)<=24000),created_at timestamptz not null default now(),submitted_at timestamptz,reviewed_at timestamptz);
create unique index one_open_role_application on public.role_applications(user_id,role) where status in ('draft','submitted','under_review');
create table public.application_publications(application_id uuid not null references public.role_applications,product_index integer not null,listing_id uuid not null references public.listings,primary key(application_id,product_index));
create table public.agreement_submissions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,application_id uuid unique references public.role_applications,agreement_id uuid not null references public.agreement_versions,kind text not null,version text not null,text_snapshot jsonb not null,source_sha256 text not null,verified_email text,typed_name text not null check(length(typed_name) between 2 and 150),signature jsonb not null check(octet_length(signature::text)<=12000),acknowledgments jsonb not null,explicit_consent boolean not null check(explicit_consent),created_at timestamptz not null default now());
create unique index customer_version_consent on public.agreement_submissions(user_id,agreement_id) where application_id is null;
create table public.agreement_documents(submission_id uuid primary key references public.agreement_submissions,path text unique,sha256 text,generated_at timestamptz,error_code text,attempts integer not null default 0);
create table public.application_assets(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.role_applications,path text unique not null,created_at timestamptz not null default now());
create table public.application_decisions(id bigint generated always as identity primary key,application_id uuid not null references public.role_applications,actor_id uuid not null references public.profiles,decision text not null check(decision in ('under_review','approved','rejected')),notes text not null default '' check(length(notes)<=2000),created_at timestamptz not null default now());
create table public.notification_deliveries(id uuid primary key default gen_random_uuid(),submission_id uuid not null unique references public.agreement_submissions,status text not null default 'queued' check(status in ('queued','sending','accepted','failed','blocked')),attempts integer not null default 0,provider_id text,available_at timestamptz not null default now(),lease_until timestamptz,error_code text,created_at timestamptz not null default now());
create table public.account_privacy(user_id uuid primary key references public.profiles,communication text not null default 'essential' check(communication in ('essential','email')),analytics_consent boolean not null default false,deletion_requested_at timestamptz);
create table public.private_addresses(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,label text not null check(length(label) between 1 and 60),address text not null check(length(address) between 8 and 500),instructions text not null default '' check(length(instructions)<=500),created_at timestamptz not null default now());
create function public.real_account() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and demo_workspace is null and not suspended and lifecycle not in ('suspended','deletion_requested'));$$;
create function public.platform_admin() returns boolean language sql stable security definer set search_path='' as $$select public.real_account() and exists(select 1 from public.profiles where id=auth.uid() and email_verified_at is not null) and exists(select 1 from public.user_roles where user_id=auth.uid() and role='admin' and status='approved');$$;
create or replace function public.has_role(wanted public.app_role) returns boolean language sql stable security definer set search_path='' as $$select public.account_active() and exists(select 1 from public.user_roles r join public.profiles p on p.id=r.user_id where r.user_id=auth.uid() and r.role=wanted and (p.demo_workspace is not null and wanted<>'admin' or r.status='approved' and p.email_verified_at is not null and (wanted<>'customer' or p.customer_terms)) and (wanted<>'admin' or p.demo_workspace is null));$$;
create or replace function public.new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,lifecycle,email_verified_at) values(new.id,case when to_jsonb(new)->>'email_confirmed_at' is null then 'pending_verification' else 'pending_review' end,(to_jsonb(new)->>'email_confirmed_at')::timestamptz);insert into public.user_roles(user_id,role,status) values(new.id,'customer','pending_verification');return new;end;$$;
create function public.sync_verified_email() returns trigger language plpgsql security definer set search_path='' as $$begin update public.profiles set email_verified_at=(to_jsonb(new)->>'email_confirmed_at')::timestamptz,lifecycle=case when lifecycle='pending_verification' and to_jsonb(new)->>'email_confirmed_at' is not null then 'pending_review' else lifecycle end where id=new.id;return new;end;$$;
create trigger phase4_email_verified after update on auth.users for each row execute function public.sync_verified_email();
create function public.immutable_agreement() returns trigger language plpgsql set search_path='' as $$begin if tg_table_name='agreement_versions' and tg_op='UPDATE' and (to_jsonb(new)-'active')=(to_jsonb(old)-'active') then return new;end if;raise exception 'Agreement evidence is immutable; create a new version';end;$$;
create trigger immutable_version before update or delete on public.agreement_versions for each row execute function public.immutable_agreement();
create trigger immutable_consent before update or delete on public.agreement_submissions for each row execute function public.immutable_agreement();
create trigger immutable_decision before update or delete on public.application_decisions for each row execute function public.immutable_agreement();
create function public.valid_application(role_name text,p jsonb) returns boolean language plpgsql immutable set search_path='' as $$declare product jsonb;k text;begin
if jsonb_typeof(p)<>'object' then return false;end if;
foreach k in array array['name','phone','serviceArea','description'] loop if jsonb_typeof(p->k) is distinct from 'string' or length(p->>k) not between 2 and (case when k='description' then 2000 else 150 end) then return false;end if;end loop;
if role_name='vendor' then
if coalesce(p->>'category','') not in ('Food','Gifts','Makers','Farm','Shops','Services') or length(coalesce(p->>'representative','')) not between 2 and 150 or jsonb_typeof(p->'products') is distinct from 'array' or jsonb_array_length(p->'products') not between 1 and 10 then return false;end if;
for product in select value from jsonb_array_elements(p->'products') loop
if jsonb_typeof(product->'priceCents') is distinct from 'number' or jsonb_typeof(product->'inventory') is distinct from 'number' or length(coalesce(product->>'title','')) not between 2 and 150 or length(coalesce(product->>'description','')) not between 2 and 2000 or coalesce(product->>'mode','') not in ('SELL','MAKE','DO') or (product->>'priceCents')::bigint not between 0 and 10000000 or (product->>'inventory')::integer not between 0 and 100000 or length(coalesce(product->>'availability','')) not between 2 and 200 or (product->>'mode'='SELL' and (product->>'priceCents')::bigint<=0) or jsonb_typeof(product->'photos') is distinct from 'array' or jsonb_array_length(product->'photos')>3 then return false;end if;end loop;
elsif role_name='runner' then
if jsonb_typeof(p->'radius') is distinct from 'number' or jsonb_typeof(p->'maxDetour') is distinct from 'number' or coalesce(p->>'transportation','') not in ('Walking','Bicycle','Car') or (p->>'radius')::numeric not between 1 and 50 or (p->>'maxDetour')::numeric not between 0 and 50 or p->'locationConsent' is distinct from 'true'::jsonb or jsonb_typeof(p->'deliveryTypes') is distinct from 'array' or jsonb_array_length(p->'deliveryTypes') not between 1 and 6 then return false;end if;
foreach k in array array['availability','travelAreas','pickupAreas','routePreferences'] loop if length(coalesce(p->>k,'')) not between 2 and 500 then return false;end if;end loop;
if exists(select 1 from jsonb_array_elements_text(p->'deliveryTypes') x where x not in ('Food','Gifts','Makers','Farm','Shops','Services')) then return false;end if;
else return false;end if;return true;exception when others then return false;end;$$;
create function public.valid_signature(s jsonb) returns boolean language plpgsql immutable set search_path='' as $$declare stroke jsonb;point jsonb;n integer=0;begin
if jsonb_typeof(s)<>'array' or jsonb_array_length(s) not between 1 and 30 then return false;end if;
for stroke in select value from jsonb_array_elements(s) loop if jsonb_typeof(stroke)<>'array' or jsonb_array_length(stroke) not between 2 and 150 then return false;end if;
for point in select value from jsonb_array_elements(stroke) loop n=n+1;if jsonb_typeof(point)<>'array' or jsonb_array_length(point)<>2 or jsonb_typeof(point->0)<>'number' or jsonb_typeof(point->1)<>'number' or (point->>0)::numeric not between 0 and 600 or (point->>1)::numeric not between 0 and 200 then return false;end if;end loop;end loop;return n<=450;exception when others then return false;end;$$;
revoke execute on function public.valid_application(text,jsonb),public.valid_signature(jsonb) from public,anon,authenticated;
create function public.save_application(application_role text,application_payload jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare a public.role_applications;begin
if not public.real_account() or application_role not in ('vendor','runner') or octet_length(application_payload::text)>24000 or not public.valid_application(application_role,application_payload) then raise exception 'Real account required';end if;
insert into public.role_applications(user_id,role,payload) values(auth.uid(),application_role,application_payload) on conflict(user_id,role) where status in ('draft','submitted','under_review') do update set payload=excluded.payload where role_applications.status='draft' returning * into a;
if a.id is null then raise exception 'Submitted applications are immutable';end if;return a.id;end;$$;
create function public.submit_application(application_id uuid,agreement_id uuid,typed_name text,signature jsonb,acknowledgments jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare a public.role_applications;v public.agreement_versions;s uuid;begin
if not public.real_account() or not exists(select 1 from public.profiles where id=auth.uid() and email_verified_at is not null) then raise exception 'Verified real email required';end if;
select * into a from public.role_applications where id=application_id and user_id=auth.uid() for update;if not found then raise exception 'Application unavailable';end if;
select id into s from public.agreement_submissions where agreement_submissions.application_id=a.id;if found then return s;end if;
if a.role='vendor' and exists(select 1 from jsonb_array_elements(a.payload->'products') product cross join lateral jsonb_array_elements_text(product->'photos') photo where not exists(select 1 from public.application_assets asset where asset.id::text=photo and asset.application_id=a.id)) then raise exception 'Private photo reference unavailable';end if;
select * into v from public.agreement_versions where id=agreement_id and kind=a.role and active;if not found then raise exception 'Current agreement unavailable';end if;
if not public.valid_application(a.role,a.payload) or not public.valid_signature(signature) or a.status<>'draft' or length(typed_name) not between 2 and 150 or jsonb_typeof(signature)<>'array' or jsonb_array_length(signature) not between 1 and 50 or octet_length(signature::text)>12000 or acknowledgments<>v.sections then raise exception 'Complete signature and acknowledgments required';end if;
insert into public.agreement_submissions(user_id,application_id,agreement_id,kind,version,text_snapshot,source_sha256,verified_email,typed_name,signature,acknowledgments,explicit_consent) values(auth.uid(),a.id,v.id,v.kind,v.version,v.sections,v.source_sha256,(select to_jsonb(u)->>'email' from auth.users u where u.id=auth.uid()),typed_name,signature,acknowledgments,true) returning id into s;
insert into public.user_roles(user_id,role,status) values(auth.uid(),a.role::public.app_role,'pending_review') on conflict do nothing;
insert into public.agreement_documents(submission_id) values(s);insert into public.notification_deliveries(submission_id) values(s);
update public.role_applications set status='submitted',submitted_at=now() where id=a.id;
insert into public.audit_events(actor_id,event,resource_id) values(auth.uid(),'APPLICATION_SUBMITTED',a.id);return s;end;$$;
create function public.accept_customer_terms(agreement_id uuid,typed_name text) returns uuid language plpgsql security definer set search_path='' as $$declare v public.agreement_versions;s uuid;begin
if not public.real_account() or not exists(select 1 from public.profiles where id=auth.uid() and email_verified_at is not null) then raise exception 'Verify your email first';end if;
select * into v from public.agreement_versions where id=agreement_id and kind='customer' and active;if not found or length(typed_name) not between 2 and 150 then raise exception 'Current terms and name required';end if;
insert into public.agreement_submissions(user_id,agreement_id,kind,version,text_snapshot,source_sha256,verified_email,typed_name,signature,acknowledgments,explicit_consent) values(auth.uid(),v.id,v.kind,v.version,v.sections,v.source_sha256,(select to_jsonb(u)->>'email' from auth.users u where u.id=auth.uid()),typed_name,'[]',v.sections,true) on conflict do nothing;
select id into s from public.agreement_submissions where user_id=auth.uid() and agreement_submissions.agreement_id=v.id;
insert into public.agreement_documents(submission_id) values(s) on conflict do nothing;
update public.profiles set customer_terms=true,lifecycle='approved' where id=auth.uid();update public.user_roles set status='approved' where user_id=auth.uid() and role='customer';return s;end;$$;
create function public.review_application(application_id uuid,decision text,notes text) returns void language plpgsql security definer set search_path='' as $$declare a public.role_applications;p public.profiles;item jsonb;vendor_id uuid;listing_id uuid;product_index integer=0;begin
if not public.platform_admin() or decision not in ('under_review','approved','rejected') or length(notes)>2000 then raise exception 'Administrator required';end if;
select * into a from public.role_applications where id=application_id for update;if not found then raise exception 'Application unavailable';end if;
if a.status=decision then return;end if;if a.status not in ('submitted','under_review') then raise exception 'Application already finalized';end if;
select * into p from public.profiles where id=a.user_id for update;
if decision='approved' then
if p.demo_workspace is not null or p.suspended or p.email_verified_at is null or p.lifecycle='deletion_requested' or not exists(select 1 from public.agreement_submissions s join public.agreement_documents d on d.submission_id=s.id where s.application_id=a.id and d.path is not null) then raise exception 'Verified identity and completed consent PDF required';end if;
insert into public.user_roles(user_id,role,status) values(a.user_id,a.role::public.app_role,'approved') on conflict(user_id,role) do update set status='approved';
if a.role='vendor' then
insert into public.vendors(owner_id,name,slug,description,category,public_lon,public_lat,demo,verified,active,service_area) values(a.user_id,a.payload->>'name','approved-'||a.id,a.payload->>'description',a.payload->>'category',-91.05,39.45,false,false,true,a.payload->>'serviceArea') returning id into vendor_id;
for item in select value from jsonb_array_elements(a.payload->'products') loop
insert into public.listings(vendor_id,title,description,category,mode,price_cents,inventory,active) values(vendor_id,item->>'title',item->>'description',a.payload->>'category',item->>'mode',(item->>'priceCents')::bigint,(item->>'inventory')::integer,true) returning id into listing_id;
insert into public.application_publications values(a.id,product_index,listing_id);product_index=product_index+1;
end loop;
else insert into public.runners(id,display_name,bio,public_lon,public_lat,transportation,categories,max_detour_miles,demo,visible) values(a.user_id,'Neighbor runner','Approved participant; identity, insurance and background checks unverified.',-91.05,39.45,a.payload->>'transportation',array(select jsonb_array_elements_text(a.payload->'deliveryTypes')),(a.payload->>'maxDetour')::numeric,false,false) on conflict(id) do nothing;end if;
end if;
if decision='rejected' then update public.user_roles set status='rejected' where user_id=a.user_id and role=a.role::public.app_role and status='pending_review';end if;
update public.role_applications set status=decision,reviewed_at=now() where id=a.id;
insert into public.application_decisions(application_id,actor_id,decision,notes) values(a.id,auth.uid(),decision,notes);
insert into public.audit_events(actor_id,event,resource_id) values(auth.uid(),'APPLICATION_'||upper(decision),a.id);end;$$;
-- Remove legacy browser role-grant bypass for reviewed real roles. Admin bootstrap is operator-only.
create or replace function public.assign_role(target_user uuid,wanted public.app_role,longitude numeric,latitude numeric) returns void language plpgsql security definer set search_path='' as $$begin
if not public.platform_admin() or wanted in ('vendor','runner','admin') then raise exception 'Use reviewed applications or operator admin bootstrap';end if;
if exists(select 1 from public.profiles where id=target_user and demo_workspace is not null) then raise exception 'Real accounts only';end if;
insert into public.user_roles(user_id,role,status) values(target_user,wanted,'approved') on conflict do nothing;end;$$;
create function public.request_account_deletion() returns void language plpgsql security definer set search_path='' as $$begin if not public.real_account() then raise exception 'Real account required';end if;insert into public.account_privacy(user_id,deletion_requested_at) values(auth.uid(),now()) on conflict(user_id) do update set deletion_requested_at=coalesce(account_privacy.deletion_requested_at,excluded.deletion_requested_at);update public.profiles set lifecycle='deletion_requested',suspended=true where id=auth.uid();insert into public.audit_events(actor_id,event,resource_id) values(auth.uid(),'ACCOUNT_DELETION_REQUESTED',auth.uid());end;$$;
create function public.claim_notification(delivery_id uuid) returns public.notification_deliveries language plpgsql security definer set search_path='' as $$declare n public.notification_deliveries;begin select * into n from public.notification_deliveries where id=delivery_id for update;if not found or n.status='accepted' or n.available_at>now() or n.lease_until>now() then return null;end if;update public.notification_deliveries set status='sending',attempts=attempts+1,lease_until=now()+interval '2 minutes' where id=n.id returning * into n;return n;end;$$;
-- Every new table is private by default; no direct writes for applications/consent/decisions.
do $$declare t text;begin foreach t in array array['application_publications','agreement_versions','role_applications','agreement_submissions','agreement_documents','application_assets','application_decisions','notification_deliveries','account_privacy','private_addresses'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant all on public.%I to service_role',t);end loop;end$$;
grant select on public.agreement_versions to anon,authenticated;
create policy agreement_read on public.agreement_versions for select using(active or public.platform_admin());
grant select on public.application_publications,public.role_applications,public.agreement_submissions,public.agreement_documents,public.application_assets,public.application_decisions,public.notification_deliveries,public.account_privacy,public.private_addresses to authenticated;
create policy publication_read on public.application_publications for select using(public.platform_admin() or exists(select 1 from public.role_applications where id=application_id and user_id=auth.uid() and public.real_account()));
create policy application_read on public.role_applications for select using(public.platform_admin() or user_id=auth.uid() and public.real_account());
create policy submission_read on public.agreement_submissions for select using(public.platform_admin() or user_id=auth.uid() and public.real_account());
create policy document_read on public.agreement_documents for select using(public.platform_admin() or exists(select 1 from public.agreement_submissions where id=submission_id and user_id=auth.uid() and public.real_account()));
create policy asset_read on public.application_assets for select using(public.platform_admin() or exists(select 1 from public.role_applications where id=application_id and user_id=auth.uid() and public.real_account()));
create policy decision_read on public.application_decisions for select using(public.platform_admin());
create policy notification_read on public.notification_deliveries for select using(public.platform_admin());
create policy privacy_read on public.account_privacy for select using(user_id=auth.uid() and public.real_account());
create policy address_read on public.private_addresses for select using(user_id=auth.uid() and public.real_account());
create policy privacy_write on public.account_privacy for all to authenticated using(user_id=auth.uid() and public.real_account()) with check(user_id=auth.uid() and public.real_account());
create policy address_write on public.private_addresses for all to authenticated using(user_id=auth.uid() and public.real_account()) with check(user_id=auth.uid() and public.real_account());
grant insert(user_id,communication,analytics_consent),update(user_id,communication,analytics_consent) on public.account_privacy to authenticated;
grant insert(user_id,label,address,instructions),delete on public.private_addresses to authenticated;
grant usage,select on sequence public.application_decisions_id_seq to service_role;
revoke execute on function public.real_account(),public.platform_admin(),public.sync_verified_email(),public.immutable_agreement(),public.save_application(text,jsonb),public.submit_application(uuid,uuid,text,jsonb,jsonb),public.accept_customer_terms(uuid,text),public.review_application(uuid,text,text),public.request_account_deletion(),public.claim_notification(uuid) from public,anon,authenticated;
grant execute on function public.real_account(),public.platform_admin() to anon,authenticated;
grant execute on function public.save_application(text,jsonb),public.submit_application(uuid,uuid,text,jsonb,jsonb),public.accept_customer_terms(uuid,text),public.review_application(uuid,text,text),public.request_account_deletion() to authenticated;
grant execute on function public.claim_notification(uuid) to service_role;
-- Reject any existing public bucket rather than silently exposing consent evidence.
do $$begin if to_regclass('storage.buckets') is not null then
if exists(select 1 from storage.buckets where id='onboarding-private' and public) then raise exception 'onboarding-private bucket must be private';end if;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('onboarding-private','onboarding-private',false,5242880,array['application/pdf','image/webp']) on conflict(id) do nothing;
execute 'create policy onboarding_no_browser_read on storage.objects as restrictive for select to anon,authenticated using(bucket_id<>''onboarding-private'')';
execute 'create policy onboarding_no_browser_insert on storage.objects as restrictive for insert to anon,authenticated with check(bucket_id<>''onboarding-private'')';
execute 'create policy onboarding_no_browser_update on storage.objects as restrictive for update to anon,authenticated using(bucket_id<>''onboarding-private'') with check(bucket_id<>''onboarding-private'')';
execute 'create policy onboarding_no_browser_delete on storage.objects as restrictive for delete to anon,authenticated using(bucket_id<>''onboarding-private'')';end if;end$$;
create table public.auth_entry_limits(key_hash text not null,window_start timestamptz not null,count integer not null,primary key(key_hash,window_start));
alter table public.auth_entry_limits enable row level security;revoke all on public.auth_entry_limits from anon,authenticated;grant all on public.auth_entry_limits to service_role;
create function public.consume_auth_entry(key_hash text) returns void language plpgsql security definer set search_path='' as $$declare n integer;begin insert into public.auth_entry_limits values(key_hash,date_trunc('minute',now()),1) on conflict on constraint auth_entry_limits_pkey do update set count=auth_entry_limits.count+1 returning count into n;if n>15 then raise exception 'Auth rate limit';end if;end;$$;
revoke execute on function public.consume_auth_entry(text) from public,anon,authenticated;grant execute on function public.consume_auth_entry(text) to service_role;
create function public.guard_application_evidence() returns trigger language plpgsql set search_path='' as $$begin if old.status<>'draft' and (new.payload is distinct from old.payload or new.user_id<>old.user_id or new.role<>old.role) then raise exception 'Submitted application evidence immutable';end if;return new;end;$$;
create trigger application_evidence before update on public.role_applications for each row execute function public.guard_application_evidence();
create function public.guard_document_evidence() returns trigger language plpgsql set search_path='' as $$begin if old.path is not null and new is distinct from old then raise exception 'Completed document reference immutable';end if;return new;end;$$;
create trigger document_evidence before update on public.agreement_documents for each row execute function public.guard_document_evidence();
revoke execute on function public.guard_application_evidence(),public.guard_document_evidence() from public,anon,authenticated;
create function public.phase4_lifecycle_guard() returns trigger language plpgsql set search_path='' as $$begin
if old.lifecycle='deletion_requested' and not new.suspended then raise exception 'Resolve deletion request through operator retention review';end if;
if new.lifecycle='deletion_requested' then new.suspended=true;
elsif new.suspended then new.lifecycle='suspended';
elsif old.suspended and not new.suspended then new.lifecycle=case when new.email_verified_at is null then 'pending_verification' when new.customer_terms then 'approved' else 'pending_review' end;end if;return new;end;$$;
create trigger lifecycle_guard before update on public.profiles for each row execute function public.phase4_lifecycle_guard();
create function public.phase4_photo_guard() returns trigger language plpgsql security definer set search_path='' as $$begin
perform 1 from public.role_applications where id=new.application_id and status='draft' for update;if not found or (select count(*) from public.application_assets where application_id=new.application_id)>=30 then raise exception 'Draft photo capacity exceeded';end if;return new;end;$$;
create trigger application_photo_guard before insert on public.application_assets for each row execute function public.phase4_photo_guard();
revoke execute on function public.phase4_lifecycle_guard(),public.phase4_photo_guard() from public,anon,authenticated;
create function public.phase4_ready() returns boolean language sql stable set search_path='' as $$select true;$$;
revoke execute on function public.phase4_ready() from public,anon,authenticated;grant execute on function public.phase4_ready() to service_role;
notify pgrst,'reload schema';
commit;
